- name: Ensure docker elasticsearch volume mapping host directories exist
  file:
    state: directory
    path: "{{ item | regex_replace('^(?P<host>.+):(?P<container>.+)$', '\\g<host>')}}"
  with_items:
    - "{{ docker_elasticsearch_directory_volumes }}"
  tags:
    - install
    - upgrade


- name: Run docker elasticsearch container
  become: true
  docker:
    docker_api_version: "{{ docker_api_version }}"
    env: "{{ docker_elasticsearch_env }}"
    expose: "{{ docker_elasticsearch_expose }}"
    image: "{{ docker_elasticsearch_image }}"
    name: "{{ docker_elasticsearch_name }}"
    ports: "{{ docker_elasticsearch_ports }}"
    links: "{{ docker_elasticsearch_links }}"
    volumes: "{{ docker_elasticsearch_volumes }}"
    log_driver: "{{ docker_elasticsearch_log_driver }}"
    log_opt: "{{ docker_elasticsearch_log_opt }}"
    pull: always
    restart_policy: always
    state: reloaded
  tags:
    - install
    - upgrade
